import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
/* ข้อดี next.js คือ
1.SEO, search engine optimization by sending pre rendered pages so that search engine crawler could better understand the web so that it ranked higher
2. file base Routing system
3. full stack app development is much easier because of "API routes" --> APi endpoint, serverless API
4. Code splitting, only load the javascript code of what's needed
Next.js is literally a react with many built-in features that help automated many functions so that dev could focus on
writing core react code
*/
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
